/* Template Args:
   1. Database Name
 */
USE [master]
GO

CREATE DATABASE [OpenKO]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OpenKO].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [OpenKO] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [OpenKO] SET ANSI_NULLS OFF
GO

ALTER DATABASE [OpenKO] SET ANSI_PADDING OFF
GO

ALTER DATABASE [OpenKO] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [OpenKO] SET ARITHABORT OFF
GO

ALTER DATABASE [OpenKO] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [OpenKO] SET AUTO_SHRINK ON
GO

ALTER DATABASE [OpenKO] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [OpenKO] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [OpenKO] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [OpenKO] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [OpenKO] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [OpenKO] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [OpenKO] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [OpenKO] SET  DISABLE_BROKER
GO

ALTER DATABASE [OpenKO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [OpenKO] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [OpenKO] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [OpenKO] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [OpenKO] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [OpenKO] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [OpenKO] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [OpenKO] SET RECOVERY SIMPLE
GO

ALTER DATABASE [OpenKO] SET  MULTI_USER
GO

ALTER DATABASE [OpenKO] SET PAGE_VERIFY NONE
GO

ALTER DATABASE [OpenKO] SET DB_CHAINING OFF
GO

ALTER DATABASE [OpenKO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [OpenKO] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [OpenKO] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [OpenKO] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [OpenKO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OpenKO] SET  READ_WRITE
GO
