/* Template Args:
   1. Database Name
 */
USE [master]
GO

CREATE DATABASE [Prototype]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Prototype].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [Prototype] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Prototype] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Prototype] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Prototype] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Prototype] SET ARITHABORT OFF
GO

ALTER DATABASE [Prototype] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Prototype] SET AUTO_SHRINK ON
GO

ALTER DATABASE [Prototype] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Prototype] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Prototype] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Prototype] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Prototype] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Prototype] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Prototype] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Prototype] SET  DISABLE_BROKER
GO

ALTER DATABASE [Prototype] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Prototype] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Prototype] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Prototype] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Prototype] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Prototype] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Prototype] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Prototype] SET RECOVERY SIMPLE
GO

ALTER DATABASE [Prototype] SET  MULTI_USER
GO

ALTER DATABASE [Prototype] SET PAGE_VERIFY NONE
GO

ALTER DATABASE [Prototype] SET DB_CHAINING OFF
GO

ALTER DATABASE [Prototype] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Prototype] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Prototype] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [Prototype] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [Prototype] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Prototype] SET  READ_WRITE
GO
