/* Template Args:
   1. Database Name
 */
USE [master]
GO

CREATE DATABASE [KN_online]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KN_online].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [KN_online] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [KN_online] SET ANSI_NULLS OFF
GO

ALTER DATABASE [KN_online] SET ANSI_PADDING OFF
GO

ALTER DATABASE [KN_online] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [KN_online] SET ARITHABORT OFF
GO

ALTER DATABASE [KN_online] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [KN_online] SET AUTO_SHRINK ON
GO

ALTER DATABASE [KN_online] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [KN_online] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [KN_online] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [KN_online] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [KN_online] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [KN_online] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [KN_online] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [KN_online] SET  DISABLE_BROKER
GO

ALTER DATABASE [KN_online] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [KN_online] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [KN_online] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [KN_online] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [KN_online] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [KN_online] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [KN_online] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [KN_online] SET RECOVERY SIMPLE
GO

ALTER DATABASE [KN_online] SET  MULTI_USER
GO

ALTER DATABASE [KN_online] SET PAGE_VERIFY NONE
GO

ALTER DATABASE [KN_online] SET DB_CHAINING OFF
GO

ALTER DATABASE [KN_online] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [KN_online] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [KN_online] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [KN_online] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [KN_online] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KN_online] SET  READ_WRITE
GO
