USE [KN_online]
GO

CREATE TABLE [BATTLE] (
	[sIndex] smallint NOT NULL,
	[byNation] tinyint NOT NULL,
	[strUserName] varchar(21),
	[byElmoArea] tinyint NOT NULL,
	[byKarusArea] tinyint NOT NULL,
	[byElmoAdvantage] tinyint NOT NULL,
	[byKarusAdvantage] tinyint NOT NULL,
	[byArea_1] tinyint NOT NULL,
	[byArea_2] tinyint NOT NULL,
	[byArea_3] tinyint NOT NULL,
	[byArea_4] tinyint NOT NULL,
	[byArea_5] tinyint NOT NULL,
	[byArea_6] tinyint NOT NULL,
	[byArea_7] tinyint NOT NULL,
	[byArea_8] tinyint NOT NULL,
	[byArea_9] tinyint NOT NULL,
	[byArea_10] tinyint NOT NULL,
	[byArea_11] tinyint NOT NULL
)
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byElmoArea] DEFAULT 0 FOR [byElmoArea]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byKarusArea] DEFAULT 0 FOR [byKarusArea]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byElmoAdvantage] DEFAULT 0 FOR [byElmoAdvantage]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byKarusAdvantage] DEFAULT 0 FOR [byKarusAdvantage]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_1] DEFAULT 0 FOR [byArea_1]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_2] DEFAULT 0 FOR [byArea_2]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_3] DEFAULT 0 FOR [byArea_3]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_4] DEFAULT 0 FOR [byArea_4]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_5] DEFAULT 0 FOR [byArea_5]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_6] DEFAULT 0 FOR [byArea_6]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_7] DEFAULT 0 FOR [byArea_7]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_8] DEFAULT 0 FOR [byArea_8]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_9] DEFAULT 0 FOR [byArea_9]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_10] DEFAULT 0 FOR [byArea_10]
GO
ALTER TABLE [BATTLE] ADD CONSTRAINT [DF_BATTLE_byArea_11] DEFAULT 0 FOR [byArea_11]
GO
