USE [KN_online]
GO

CREATE TABLE [ITEMUP_PROBABILITY] (
	[bType] tinyint NOT NULL,
	[nMaxSuccess] smallint NOT NULL,
	[nMaxFail] smallint NOT NULL,
	[nCurSuccess] smallint NOT NULL,
	[nCurFail] smallint NOT NULL
	CONSTRAINT [PK_ITEMUP_PROBABILITY] PRIMARY KEY CLUSTERED ([bType])
)
GO
ALTER TABLE [ITEMUP_PROBABILITY] ADD CONSTRAINT [DF_ITEMUP_PROBABILITY_nMaxSuccess] DEFAULT 0 FOR [nMaxSuccess]
GO
ALTER TABLE [ITEMUP_PROBABILITY] ADD CONSTRAINT [DF_ITEMUP_PROBABILITY_nMaxFail] DEFAULT 0 FOR [nMaxFail]
GO
ALTER TABLE [ITEMUP_PROBABILITY] ADD CONSTRAINT [DF_ITEMUP_PROBABILITY_nCurSuccess] DEFAULT 0 FOR [nCurSuccess]
GO
ALTER TABLE [ITEMUP_PROBABILITY] ADD CONSTRAINT [DF_ITEMUP_PROBABILITY_nCurFail] DEFAULT 0 FOR [nCurFail]
GO
