USE [KN_online]
GO

CREATE TABLE [KNIGHTS_SIEGE_WARFARE] (
	[sCastleIndex] smallint NOT NULL,
	[sMasterKnights] smallint NOT NULL,
	[bySiegeType] tinyint NOT NULL,
	[byWarDay] tinyint NOT NULL,
	[byWarTime] tinyint NOT NULL,
	[byWarMinute] tinyint NOT NULL,
	[sChallengeList_1] smallint NOT NULL,
	[sChallengeList_2] smallint NOT NULL,
	[sChallengeList_3] smallint NOT NULL,
	[sChallengeList_4] smallint NOT NULL,
	[sChallengeList_5] smallint NOT NULL,
	[sChallengeList_6] smallint NOT NULL,
	[sChallengeList_7] smallint NOT NULL,
	[sChallengeList_8] smallint NOT NULL,
	[sChallengeList_9] smallint NOT NULL,
	[sChallengeList_10] smallint NOT NULL,
	[byWarRequestDay] tinyint NOT NULL,
	[byWarRequestTime] tinyint NOT NULL,
	[byWarRequestMinute] tinyint NOT NULL,
	[byGuerrillaWarDay] tinyint NOT NULL,
	[byGuerrillaWarTime] tinyint NOT NULL,
	[byGuerrillaWarMinute] tinyint NOT NULL,
	[strChallengeList] char(50),
	[sMoradonTariff] smallint NOT NULL,
	[sDellosTariff] smallint NOT NULL,
	[nDungeonCharge] int NOT NULL,
	[nMoradonTax] int NOT NULL,
	[nDellosTax] int NOT NULL,
	[sRequestList_1] smallint NOT NULL,
	[sRequestList_2] smallint NOT NULL,
	[sRequestList_3] smallint NOT NULL,
	[sRequestList_4] smallint NOT NULL,
	[sRequestList_5] smallint NOT NULL,
	[sRequestList_6] smallint NOT NULL,
	[sRequestList_7] smallint NOT NULL,
	[sRequestList_8] smallint NOT NULL,
	[sRequestList_9] smallint NOT NULL,
	[sRequestList_10] smallint NOT NULL
)
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sChallengeList_7] DEFAULT 0 FOR [sChallengeList_7]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sChallengeList_8] DEFAULT 0 FOR [sChallengeList_8]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sChallengeList_9] DEFAULT 0 FOR [sChallengeList_9]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sChallengeList_10] DEFAULT 0 FOR [sChallengeList_10]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_byWarRequestDay] DEFAULT 3 FOR [byWarRequestDay]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_byWarRequestTime] DEFAULT 9 FOR [byWarRequestTime]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_byWarRequestMinute] DEFAULT 0 FOR [byWarRequestMinute]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_byGuerrillaWarDay] DEFAULT 1 FOR [byGuerrillaWarDay]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_byGuerrillaWarTime] DEFAULT 20 FOR [byGuerrillaWarTime]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_byGuerrillaWarMinute] DEFAULT 0 FOR [byGuerrillaWarMinute]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sMoradonTariff] DEFAULT 0 FOR [sMoradonTariff]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sDellosTariff] DEFAULT 0 FOR [sDellosTariff]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_nDungeonCharge] DEFAULT 0 FOR [nDungeonCharge]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_nMoradonTax] DEFAULT 0 FOR [nMoradonTax]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_nDellosTax] DEFAULT 0 FOR [nDellosTax]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_1] DEFAULT 0 FOR [sRequestList_1]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_2] DEFAULT 0 FOR [sRequestList_2]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_3] DEFAULT 0 FOR [sRequestList_3]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_4] DEFAULT 0 FOR [sRequestList_4]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_5] DEFAULT 0 FOR [sRequestList_5]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_6] DEFAULT 0 FOR [sRequestList_6]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_7] DEFAULT 0 FOR [sRequestList_7]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_8] DEFAULT 0 FOR [sRequestList_8]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_9] DEFAULT 0 FOR [sRequestList_9]
GO
ALTER TABLE [KNIGHTS_SIEGE_WARFARE] ADD CONSTRAINT [DF_KNIGHTS_SIEGE_WARFARE_sRequestList_10] DEFAULT 0 FOR [sRequestList_10]
GO
