INSERT INTO [SERVER_RESOURCE] ([nResourceID], [strName], [strResource]) VALUES
(103, N'IDP_SOCKETS_INIT_FAILED', N'Failed initializing Windows socket'),
(105, N'IDP_BATTLEZONE_OPEN', N'Lunar Gate is now open.  The War has begun.'),
(106, N'IDP_KARUS_VICTORY', N'Karus is victorious. They killed %d warriors and lost %d warriors'),
(107, N'IDP_ELMORAD_VICTORY', N'El Morad is victorious. They killed %d warriors and lost %d warriors'),
(108, N'IDP_KARUS_BANISH', N'El Morad warriors in the battle zone have been banned!'),
(109, N'IDP_ELMORAD_BANISH', N'Karus warriors in the battle zone have been banned!'),
(110, N'IDP_KNIGHT_NAME_REPEAT', N'This Knights name already exist.'),
(111, N'IDP_KNIGHT_ALREADY_REGISTERED', N'You are already in a Knights'),
(112, N'IDP_KNIGHT_INSUFFICIENT_LEVEL', N'You need to be at least at Level 20 in order to create a Knights'),
(113, N'IDP_KNIGHT_INSUFFICIENT_LOYALTY', N'You need to have at least 800 National Points in order to create a Knights'),
(114, N'IDP_KNIGHT_INSUFFICIENT_SKILL', N'You need to have at least 10 Leadership skill points and 5 Manner skill points in order to create a'),
(115, N'IDP_KNIGHT_INSUFFICIENT_CHARISMA', N'You need to have at least 120 Attractactiveness skill points in order to create a Knights'),
(116, N'IDP_KNIGHT_INSUFFICIENT_GOLD', N'You need to have at least 1,000,000 Coins in order to create a Knights'),
(117, N'IDP_KNIGHT_CREATE_FAIL', N'You have failed creating a Knights'),
(118, N'IDP_KNIGHT_NOT_AVAILABLE', N'This Knights does not exist'),
(119, N'IDP_KNIGHT_LEADER_ONLY', N'This is authorized for Head of Knights only.'),
(120, N'IDP_KNIGHT_MINIMUM_SUBLEADER', N'This is authorized for ranks higher than Vice Head of Knights only.'),
(121, N'IDP_KNIGHT_NOT_REGISTERED', N'Not Register Knights'),
(122, N'IDP_KNIGHT_DB_FAIL', N'Failed Update DB with Knights'),
(123, N'IDP_WRONG_ID', N'This ID does not exist'),
(124, N'IDP_SOURCE_UNABLE', N'Source Unable'),
(125, N'IDP_MINIMUM_OFFICER', N'This is authorized for ranks higher than officer'),
(126, N'IDP_ANNOUNCEMENT', N'#### NOTICE : %s ####'),
(130, N'IDS_ELMORAD_LOSER', N'El Morad have lost the war. They killed [%d] warriors and lost [%d] warriors'),
(131, N'IDS_KARUS_LOSER', N'Karus have lost the war. They killed [%d] warriors and lost [%d] warriors'),
(132, N'IDS_BANISH_USER', N'Users in the Lunar Valley and the enemy’s territory will be teleported back to their own Nations.'),
(133, N'IDS_BATTLE_CLOSE', N'Lunar Gate is closing.'),
(134, N'IDS_KILL_GATEKEEPER', N'The user that killed the enemy’s gatekeeper is [%s][%s]. Congratulations!!'),
(135, N'IDS_KILL_CAPTAIN', N'The user that killed the enemy’s captain is [%s][%s]. Congratulations!!'),
(136, N'IDS_KILL_KARUS_GUARD1', N'The sentry at the 1st Karus fortress has been killed. The user that killed the sentry is [%s][%s]'),
(137, N'IDS_KILL_KARUS_GUARD2', N'The sentry at the 2nd Karus fortress has been killed. The user that killed the sentry is [%s][%s]'),
(138, N'IDS_KILL_ELMO_GUARD1', N'The sentry at the 1st El Morad fortress has been killed. The user that killed the sentry is [%s][%s]'),
(139, N'IDS_KILL_ELMO_GUARD2', N'The sentry at the 2nd El Morad fortress has been killed. The user that killed the sentry is [%s][%s]'),
(140, N'IDS_KARUS_CAPTAIN', N'The captain(s) for Karus is(are) %s, %s, %s, %s, %s'),
(141, N'IDS_ELMO_CAPTAIN', N'The captain(s) for El Morad is(are) %s, %s, %s, %s, %s'),
(142, N'IDS_KARUS_CAPTAIN_DEPRIVE', N'[%s][%s], the captain for Karus has been killed'),
(143, N'IDS_ELMO_CAPTAIN_DEPRIVE', N'[%s][%s], the captain for El Morad has been killed'),
(144, N'IDS_COUPON_NOTEPAD_ID', N'3572-8471-3720-2495'),
(145, N'IDS_COUPON_POSTIT_ID', N'7352-6539-3720-2495'),
(146, N'IDS_KNIGHTS_JOIN', N'#### %s has joined. ####'),
(147, N'IDS_KNIGHTS_WITHDRAW', N'#### %s has left. ####'),
(148, N'IDS_KNIGHTS_REMOVE', N'#### %s has been banned. ####'),
(149, N'IDS_KNIGHTS_CHIEF', N'#### %s has been appointed as a leader. ####'),
(150, N'IDS_KNIGHTS_VICECHIEF', N'#### %s has been appointed as a co-leader. ####'),
(151, N'IDS_KNIGHTS_DESTROY', N'#### the knights %s has disbanded ####'),
(152, N'IDS_CLAN_DESTORY', N'#### the clan %s has disbanded ####'),
(153, N'IDS_CLANGAME_VICTORY', N'The Clan %s has won the clan duel.'),
(154, N'IDS_CLANGAME_JOIN', N'*** %s(Lv %d)has entered the Arena Lobby ***'),
(155, N'IDS_CLANGAME_EXIT', N'*** %s(Lv %d)has left ***'),
(156, N'IDS_SNOWBATTLE_OPEN', N'The Snow Fight Zone is now open'),
(157, N'IDS_SNOWBATTLE_CLOSE', N'The Snow Fight Zone is now closed'),
(158, N'IDS_SNOWBATTLE_BANISH_USER', N'The users in the Snow Fight Zone will be teleported back to their native country.'),
(159, N'IDS_BATTLEZONE_STATUS', N'Number of killed Karus users : %d, Number of killed El Morad users : %d'),
(160, N'IDS_BANISH_LOSER', N'The users of the defeated nation in Lunar Valley will be teleported back to their native country.'),
(161, N'IDS_INFILTRATION', N'The victorious nation can invade the opposite nation.'),
(162, N'IDS_UNDER_ATTACK_KARUS', N'Karus is being invaded.'),
(163, N'IDS_UNDER_ATTACK_ELMORAD', N'El Morad is being invaded.'),
(164, N'IDS_INSERT_KNIGHTS_ALLIANCE', N'The Knights %s has entered the confederacy.'),
(165, N'IDS_REMOVE_KNIGHTS_ALLIANCE', N'The Knights %s has left the confederacy.'),
(166, N'IDS_PUNISH_KNIGHTS_ALLIANCE', N'The alliance with the Knights %s has been canceled'),
(167, N'IDS_PERSONAL_GAME_VICTORY', N'%s has won the fight'),
(168, N'IDS_DEATH_ANNOUNCEMENT', N'*** %s has defeated %s ***'),
(169, N'IDS_SIEGE_WAR_READY_TIME', N'Castle Siege War is about to begin. The designated Knights should enter the Castle Siege War zone.'),
(170, N'IDS_SIEGE_WAR_BASE_TIME', N'This is a time for building your base. Please build your base.'),
(171, N'IDS_SIEGE_WAR_START', N'The Castle Siege War has begun!'),
(172, N'IDS_SIEGE_WAR_END', N'The Castle Siege War has ended!'),
(173, N'IDS_SIEGE_WAR_READY_TIME_NOTICE', N'There are %d minutes remaining until the Castle Siege War. Knights should enter the CSW now.'),
(174, N'IDS_CHALLENGER_REQUEST_START_NOTICE', N'We are currently accepting challengers for Castle Siege War. Location Moradon : 351,400'),
(175, N'IDS_CHALLENGER_REQUEST_END_NOTICE', N'The registration period for Castle Siege War has now ended.'),
(176, N'IDS_SIEGE_WAR_GUIDON_TIME_NOTICE', N'There are %d minutes remaining for building your base. If you don''t build a base by then, you''ll aut'),
(177, N'IDS_SIEGE_WAR_TIME_NOTICE', N'There are %d minutes remaining in the war.'),
(178, N'IDS_NPC_GUIDON_DESTORY', N'The base of the Knights %s has been destroyed.'),
(179, N'IDS_NPC_DESTORY_ARTIFACT', N'Center Artifact has been destroyed'),
(180, N'IDS_NPC_DESTORY_ARTIFACT_S1', N'Sentry Artifact has been destroyed'),
(181, N'IDS_NPC_DESTORY_ARTIFACT_S2', N'Guard Tower Artifact has been destroyed'),
(182, N'IDS_NPC_DESTORY_ARTIFACT_S3', N'Defense Artifact has been destroyed'),
(184, N'IDS_NPC_DESTORY_ARTIFACT_S4', N'Shield Artifact has been destroyed'),
(185, N'IDS_GUARD_TOWER_DEATH_ANNOUNCEMENT', N'*** %s was killed by %s ***'),
(186, N'IDS_SIEGE_WAR_VICTORY', N'The clan %s is victorious!'),
(187, N'IDS_MONEY_REPAY_EVENT', N'Coin event has started. You will earn an additional %d percent of coins for killing mobs.'),
(188, N'IDS_PRE_BATTLE_ANNOUNCEMENT', N'There are 5 minutes remaining until the war commences.'),
(189, N'IDS_INFILTRATION_CONQUER', N'%s has been overrun'),
(190, N'IDS_INFILTRATION_RECAPTURE', N'%s has been captured'),
(191, N'IDS_INFILTRATION_REWARD_KARUS', N'%s has blessed the Karus warriors'),
(192, N'IDS_INFILTRATION_REWARD_ELMORAD', N'%s has blessed the El Morad warriors'),
(193, N'IDS_SERVER_AUTO_DOWN', N'The server will shutdown after %d minutes.'),
(194, N'IDS_NPC_DESTORY_ARTIFACT_CLAN', N'%s clan has destroyed the Center Artifact.'),
(195, N'IDS_ASSAULT_EVENT_START', N'We''re under attack by monsters. Please save the World from the monsters!!'),
(196, N'IDS_ASSAULT_EVENT_END', N'The monsters have stopped. The World is safe now.'),
(197, N'IDS_EXP_REPAY_EVENT', N'Experience point event Started. You will Earn %d Percent of Experience for killing Mobs.'),
(198, N'IDS_MONSTER_CHALLENGE_ANNOUNCEMENT', N'The Forgotten Temple Event will start at %d for levels %d~%d'),
(199, N'IDS_MONSTER_CHALLENGE_OPEN', N'The gate to the Forgotten Temple is now open.'),
(200, N'IDS_MONSTER_CHALLENGE_START', N'The Monsters are appearing, Get ready!!!'),
(201, N'IDS_MONSTER_CHALLENGE_VICTORY', N'You have eliminated all the monsters in the temple. You''ve received the treasure chest.'),
(202, N'IDS_MONSTER_CHALLENGE_CLOSE', N'Forgotten Temple is now over. Users remaining in the Forgotten Temple zone will be Teleported out.'),
(203, N'IDS_MID_LEVEL_BATTLEZONE_OPEN', N'Dark Lunar Gate is now open. The war has begun.'),
(204, N'IDS_KING_RECOMMEND_TIME', N'Please nominate a King.'),
(205, N'IDS_KING_RECOMMEND_FINISH_TIME', N'The period for nomination has ended.'),
(206, N'IDS_KING_ELECTION_TIME', N'Election is in progress for selecting a King.'),
(207, N'IDS_KING_IMPEACHMENT_REQUEST_TIME', N'A request for an impeachment of King has been made.'),
(208, N'IDS_KING_IMPEACHMENT_ELECTION_TIME', N'election in progress for impeaching a King.'),
(209, N'IDS_KING_REIGN_TIME', N'A new King has been appointed.'),
(210, N'IDS_KING_KARUS_PRIZE_EVENT_MESSAGE', N'The Karus King has awarded %s %d coins as a reward.'),
(211, N'IDS_KING_KARUS_FUGITIVE_EVENT_MESSAGE_1', N'The Karus King has awarded %s %d coins as a reward.'),
(212, N'IDS_KING_FUGITIVE_EVENT_MESSAGE_2', N'%s killed %s and received %d coins as a reward.'),
(213, N'IDS_KING_ELMO_PRIZE_EVENT_MESSAGE', N'The ElMorad King has awarded %s %d coins as a reward.'),
(214, N'IDS_KING_ELMO_FUGITIVE_EVENT_MESSAGE_1', N'The El Morad King has awarded %s %d coins as a reward.'),
(215, N'IDS_KING_KARUS_WEATHER_FINE_EVENT', N'The Karus King has cleared the weather.'),
(216, N'IDS_KING_KARUS_WEATHER_RAIN_EVENT', N'The Karus King has summoned the rain clouds.'),
(217, N'IDS_KING_KARUS_WEATHER_SNOW_EVENT', N'The Karus King has summoned the snow storm.'),
(218, N'IDS_KING_ELMO_WEATHER_FINE_EVENT', N'The El Morad King has cleared the weather.'),
(219, N'IDS_KING_ELMO_WEATHER_RAIN_EVENT', N'The El Morad King has summoned the rain clouds.'),
(220, N'IDS_KING_ELMO_WEATHER_SNOW_EVENT', N'The El Morad King has summoned the snow storm.'),
(221, N'IDS_KING_KARUS_NOAH_BONUS_EVENT', N'The Karus King has initiated the %d (percent) increased item drop rate event.'),
(222, N'IDS_KING_KARUS_EXP_BONUS_EVENT', N'The Karus King has initiated the %d (percent) increased experience point event.'),
(223, N'IDS_KING_ELMO_NOAH_BONUS_EVENT', N'The El Morad King has initiated the %d (percent) increased item drop rate event.'),
(224, N'IDS_KING_ELMO_EXP_BONUS_EVENT', N'The El Morad King has initiated the %d (percent) increased experience point event.'),
(225, N'IDS_KING_RECOMMEND_REQUEST_MESSAGE', N'User %s can nominate a King. Please nominate a King.'),
(226, N'IDS_KING_CANDIDACY_RECOMMEND_MESSAGE', N'%s has nominated %s as a King.'),
(227, N'IDS_KING_PERIOD_OF_RECOMMEND_MESSAGE', N'This is a period for nominating a King. Users with nomination rights should nominate a King.'),
(228, N'IDS_KING_PERIOD_OF_ELECTION_MESSAGE', N'King election period is on. Users that have not voted yet should vote for a King.'),
(229, N'IDS_KING_ELECTION_RESULT_MESSAGE', N'%d(percent) of the vote was won by %s to become a King.'),
(230, N'IDS_KING_EXP_BONUS_EVENT_STOP', N'The increased experience point event has ended.'),
(231, N'IDS_KING_ITEMDROP_BONUS_EVENT_STOP', N'The increased item drop rate event has ended.'),
(232, N'IDS_KING_IMPEACHMENT_REQUEST_MESSAGE', N'Inpeachment Request In Progress'),
(233, N'IDS_KING_IMPEACHMENT_PASS_MESSAGE', N'Inpeachment successfull'),
(234, N'IDS_KING_IMPEACHMENT_REJECT_MESSAGE', N'Inpeachment has been Rejected'),
(235, N'IDS_KING_IMPEACHMENT_ELECTION_MESSAGE', N'Please elect for your Inpeachment'),
(236, N'IDS_KING_IMPEACHMENT_ELECTION_YES_RESULT_MESSAGE', N'Inpeachment Election has been accepted'),
(237, N'IDS_KING_IMPEACHMENT_ELECTION_NO_RESULT_MESSAGE', N'Inpeachment Election has been Declined'),
(238, N'IDS_BEEF_ROAST_START', N'Bifrost event has started!'),
(239, N'IDS_BEEF_ROAST_VICTORY_KARUS', N'The Karus warriors have destroyed the monument and can now enter Bifrost!'),
(240, N'IDS_BEEF_ROAST_VICTORY_ELMORAD', N'The El Morad warriors have destroyed the monument and can now enter Bifrost!'),
(241, N'IDS_BEEF_ROAST_FINISH', N'Bifrost event is now over!'),
(242, N'IDS_BEEF_ROAST_DRAW', N'Nobody has won the Bifrost event, it''s a draw!')
