/****** Object:  Stored Procedure dbo.CHANGE_COPY_SERIAL_ITEM    Script Date: 6/6/2006 6:03:34 PM ******/
CREATE PROCEDURE [CHANGE_COPY_SERIAL_ITEM]
AS
EXEC CHANGE_COPY_SERIAL_ITEM_TABLE
EXEC CHANGE_COPY_SERIAL_ITEM_DATA
