/****** Object:  Stored Procedure dbo.CHANGE_COPY_SERIAL_ITEM_TABLE    Script Date: 6/6/2006 6:03:32 PM ******/
CREATE PROCEDURE 
[dbo].[CHANGE_COPY_SERIAL_ITEM_TABLE]
AS

ALTER TABLE COPY_SERIAL_ITEM 
ADD nItemSerial BIGINT

ALTER TABLE COPY_SERIAL_ITEM 
ADD nItemNum INT

ALTER TABLE COPY_SERIAL_ITEM 
ADD strItemName VARCHAR(50)

ALTER TABLE COPY_SERIAL_ITEM 
ADD sIndex INT IDENTITY
